"use client";
import { selectGlobal } from "@/app/store/globalSlice"
import { useAppSelector } from "@/app/store/hooks"

export default function PoweredBy({ language }: { language: 'chinese' | 'english' | 'japanese' }) {
    const global = useAppSelector(selectGlobal)

    return <div
        className="flex justify-center items-center flex-col my-3 mx-auto w-full"
        style={{ color: "rgb(102, 102, 102)", fontSize: "12px" }}
    >
        <div>
            {{ chinese: "内容由AI生成，仅供参考", english: "Content generated by AI, for reference only", japanese: 'コンテンツは参照用にAIによって生成される' }[language]}
        </div>
        <div className="flex justify-center items-center gap-1">
            Powered By
            <a target="_blank" href={global.region ? "https://302.ai/" : "https://302ai.cn/"}><img className="object-contain" src="https://file.302.ai/gpt/imgs/91f7b86c2cf921f61e8cf9dc7b1ec5ee.png" alt="gpt302" width="55" /></a>
        </div>
    </div >
}