# 使用 Node 作为基础镜像
FROM node:20.17.0 AS base

FROM base AS deps

# 设置工作目录
WORKDIR /app

# 复制根目录下的 package.json 和 pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./

# 安装 pnpm 和依赖
RUN npm install -g pnpm && pnpm install --frozen-lockfile

# 复制所有文件
COPY . .

# 在根目录打包项目
RUN pnpm run build:dev

# 进入到 apps/web 目录启动
WORKDIR /app/apps/web

# 暴露端口
EXPOSE 3049

# 启动服务
CMD ["pnpm", "start"]
