# 使用 Node 作为基础镜像
FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/node:20.17.0-bullseye AS base

# 设置工作目录
WORKDIR /app

# 复制根目录下的 package.json 和 pnpm-lock.yaml
#COPY package.json *.yaml ./
# 复制 apps/web 目录下的 package.json
#COPY apps/web/package.json ./apps/web/
#COPY packages/headless/package.json ./packages/headless/
# 复制所有文件到容器

COPY . .
WORKDIR /app
# 安装 pnpm 和依赖
# 设置 Node.js 内存限制.npmmirror.com/ && \
ENV NODE_OPTIONS="--max_old_space_size=4096"
RUN npm config set registry https://registry.npmmirror.com/ && \
    npm install -g pnpm && \
    pnpm config set registry https://registry.npmmirror.com/ && \
    pnpm install --frozen-lockfile
COPY . .
WORKDIR /app
# 在 /app 目录下执行构建命令
#RUN pnpm run build:dev

#COPY . . 切换到应用目录
#WORKDIR /app/apps/web

# 暴露端口
#EXPOSE 3049

# 启动服务
#CMD ["pnpm", "start"]